name: Java booking-api

on:
  push:
    branches:
      - '*' # Run on all branches

jobs:
  build:
    runs-on: macOS

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      # If you need to set up Maven, uncomment the following lines
      #- name: Set up Maven
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y maven
      #  # Adjust this command if you want to use a specific version of Maven

      - name: Build with Maven
        run: mvn clean install # Adjust this command for your Maven build

      - name: Run Tests
        run: mvn test # Adjust this command for your Maven build
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
              test-results/**/*.xml
              # test-results/**/*.trx
              # test-results/**/*.json
