name: Java CI

on:
  push:
    branches:
      - '*' # Run on all branches

jobs:
  build:
    runs-on: macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17' # Use Java 17 provided by temurin
          distribution: 'temurin'

      # If you need to set up Maven, uncomment the following lines
      #- name: Set up Maven
      #  run: |
      #    sudo apt-get update
      #    sudo apt-get install -y maven
      #  # Adjust this command if you want to use a specific version of Maven

      - name: Build with Maven
        run: mvn clean install # Adjust this command for your Maven build

      - name: Run Tests
        run: mvn test # Adjust this command for your Maven build
